version: '3.3'

services:
  nodejs:
    build:
      context: ./nodejs/
      dockerfile: Dockerfile
    depends_on:
      - api
    volumes:
      - ./ticketnft:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    command: sh -c "yarn && yarn dev"
    ports:
      - "3000:3000"
    networks:
      - frontend
    tty: true

  api:
    # tty: true
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api/src:/go/src/app
    networks:
      - frontend
      - backend

  db:
    image: mysql:5.7
    build:
      context: ./db/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - ./db/conf:/etc/mysql/conf.d 
      - ./db/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  frontend:
  backend:
volumes:
  node-modules:
