import './globals.css'
import { Inter, Noto_Sans_JP } from 'next/font/google'

const noto_Sans_JP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
})

export const metadata = {
  title: 'Ticket NFT App',
  description: 'Generated by create next app',
  charset: 'utf-8',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="JP">
      <body className={noto_Sans_JP.className}>{children}</body>
    </html>
  )
}
