FROM node:18.16.1-alpine
WORKDIR /usr/src/app

# RUN npm install -g npm@9.7.2
# RUN npm install -g yarn
# RUN yarn global add create-next-app
# RUN yarn global add serverless-mysql
RUN yarn add next-auth
